---
- name: Execute Terraform (destroy)
  hosts: localhost
  tasks:
    - name: Get Elastic IP
      shell: terraform -chdir=../roles/ubuntu/aws/terraform/persistent output -raw eip_ip
      register: eip_id
      changed_when: false

    - name: Destroy Infastructure
      community.general.terraform:
        project_path: "../roles/ubuntu/aws/terraform/infastructure"
        state: absent
        force_init: true
        variables: 
          my_eip: "{{ eip_id.stdout }}"